version: '3.8'

services:
  # Augur Application (using your existing database)
  augur_app:
    build: .
    container_name: augur_app
    environment:
      # Use your existing database credentials from .env file
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
    restart: unless-stopped
    # Use bridge network to access your external database
    networks:
      - augur_network

  # Optional: pgAdmin for database management (if you want it)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: augur_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@augur.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - augur_network
    profiles:
      - admin

volumes:
  pgadmin_data:
    driver: local

networks:
  augur_network:
    driver: bridge